# Generated by Django 6.0.4 on 2026-05-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Digimon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('attribute', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=50)),
                ('form', models.CharField(max_length=50)),
                ('hatch', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=10)),
                ('digi_class', models.CharField(max_length=10)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('families', models.JSONField(default=list)),
                ('is_reborn', models.CharField(default='False', max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('evo_from', models.JSONField(default=list)),
                ('evo_to', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
            ],
        ),
    ]
