# Generated by Django 6.0.4 on 2026-05-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digimons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimon',
            name='digi_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='digimon',
            name='rank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
