# Generated by Django 6.0.4 on 2026-05-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digimons', '0002_alter_digimon_digi_class_alter_digimon_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimon',
            name='hatch',
            field=models.CharField(default=5, max_length=10),
        ),
        migrations.AlterField(
            model_name='digimon',
            name='size',
            field=models.CharField(default=140.0, max_length=10),
        ),
    ]
