# Generated by Django 6.0.4 on 2026-05-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digimons', '0003_alter_digimon_hatch_alter_digimon_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='digimons/'),
        ),
    ]
