# Generated by Django 6.0.4 on 2026-05-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digimons', '0004_alter_digimon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimon',
            name='evo_from',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='digimon',
            name='evo_to',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='digimon',
            name='families',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='digimon',
            name='stats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
